### ISSUE TITLE
Is letsencrypt-dcos still maintained?

### ISSUE THREAD

**Issue by Jeeppler** [mesosphere/letsencrypt-dcos#15]
Is letsencrypt-dcos still maintained? Certbot is now in version 0.20. The latest release of letsencrypt-dcos v1.0.3 contains Certbot 0.8.1.

**Comment by mattj-io** [comment]
It hasn't been for a while, but I am just looking at merging existing PR's and updating.

**Comment by mattj-io** [comment]
This project has now moved to https://github.com/dcos-labs/letsencrypt-dcos, where the latest code can be found - big improvements to performance, new Docker image, new certbot and support for custom Boulder servers.
